//
//  Assets.h
//  bomber-party
//
//  Created by Stephen Gowen on 2/22/14.
//  Copyright (c) 2014 Techne Games. All rights reserved.
//

#ifndef __bomber_party__Assets__
#define __bomber_party__Assets__

#define MAX_SOUNDS_TO_PLAY_PER_FRAME 3

// Music Definitions
#define MUSIC_STOP 1
#define MUSIC_PLAY 2

// Sound Definitions
#define SOUND_PLANT_BOMB 1
#define SOUND_EXPLOSION 2
#define SOUND_DEATH 3

// Texture Definitions
#define GAME_TEXTURE_WIDTH 1024
#define GAME_TEXTURE_HEIGHT 1024

// Texture Region Definitions
#define WORLD_BACKGROUND_TEXTURE_REGION_X 488
#define WORLD_BACKGROUND_TEXTURE_REGION_Y 432
#define WORLD_BACKGROUND_TEXTURE_REGION_WIDTH 478
#define WORLD_BACKGROUND_TEXTURE_REGION_HEIGHT 592

#define INSIDE_BLOCK_TEXTURE_REGION_X 256
#define INSIDE_BLOCK_TEXTURE_REGION_Y 80
#define BREAKABLE_BLOCK_TEXTURE_REGION_X 280
#define BREAKABLE_BLOCK_TEXTURE_REGION_Y 80
#define INSIDE_BLOCK_TEXTURE_REGION_WIDTH 16
#define INSIDE_BLOCK_TEXTURE_REGION_HEIGHT 20

#define BOMB_POWER_UP_TEXTURE_REGION_X 256
#define BOMB_POWER_UP_TEXTURE_REGION_Y 131
#define BOMB_POWER_UP_TEXTURE_REGION_WIDTH 16
#define BOMB_POWER_UP_TEXTURE_REGION_HEIGHT 20

#define SPEED_POWER_UP_TEXTURE_REGION_X 256
#define SPEED_POWER_UP_TEXTURE_REGION_Y 108
#define SPEED_POWER_UP_TEXTURE_REGION_WIDTH 16
#define SPEED_POWER_UP_TEXTURE_REGION_HEIGHT 20	

#define FIRE_POWER_UP_TEXTURE_REGION_X 280
#define FIRE_POWER_UP_TEXTURE_REGION_Y 108
#define FIRE_POWER_UP_TEXTURE_REGION_WIDTH 16
#define FIRE_POWER_UP_TEXTURE_REGION_HEIGHT 20

#define KICK_POWER_UP_TEXTURE_REGION_X 280
#define KICK_POWER_UP_TEXTURE_REGION_Y 131
#define KICK_POWER_UP_TEXTURE_REGION_WIDTH 16
#define KICK_POWER_UP_TEXTURE_REGION_HEIGHT 20

#define INTERFACE_OVERLAY_TEXTURE_REGION_X 0
#define INTERFACE_OVERLAY_TEXTURE_REGION_Y 728
#define INTERFACE_OVERLAY_TEXTURE_REGION_WIDTH 478
#define INTERFACE_OVERLAY_TEXTURE_REGION_HEIGHT 296

#define DIRECTIONAL_CONTROL_TEXTURE_REGION_X 0
#define DIRECTIONAL_CONTROL_TEXTURE_REGION_Y 576
#define DIRECTIONAL_CONTROL_TEXTURE_REGION_WIDTH 125
#define DIRECTIONAL_CONTROL_TEXTURE_REGION_HEIGHT 125

#define ACTIVE_BUTTON_TEXTURE_REGION_X 0
#define ACTIVE_BUTTON_TEXTURE_REGION_Y 489
#define ACTIVE_BUTTON_TEXTURE_REGION_WIDTH 80
#define ACTIVE_BUTTON_TEXTURE_REGION_HEIGHT 80

#define PLAYER_TEXTURE_REGION_Y 0
#define PLAYER_TEXTURE_REGION_WIDTH 20
#define PLAYER_TEXTURE_REGION_HEIGHT 30

#define PLAYER_RIGHT_IDLE_TEXTURE_REGION_X 496
#define PLAYER_RIGHT_STEP_RIGHT_TEXTURE_REGION_X 472
#define PLAYER_RIGHT_STEP_LEFT_TEXTURE_REGION_X 520

#define PLAYER_UP_IDLE_TEXTURE_REGION_X 424
#define PLAYER_UP_STEP_RIGHT_TEXTURE_REGION_X 448
#define PLAYER_UP_STEP_LEFT_TEXTURE_REGION_X 400

#define PLAYER_LEFT_IDLE_TEXTURE_REGION_X 280
#define PLAYER_LEFT_STEP_RIGHT_TEXTURE_REGION_X 256
#define PLAYER_LEFT_STEP_LEFT_TEXTURE_REGION_X 304

#define PLAYER_DOWN_IDLE_TEXTURE_REGION_X 352
#define PLAYER_DOWN_STEP_RIGHT_TEXTURE_REGION_X 376
#define PLAYER_DOWN_STEP_LEFT_TEXTURE_REGION_X 328

#define PLAYER_DEATH_TEXTURE_REGION_Y 40
#define PLAYER_DEATH_FRAME_1_TEXTURE_REGION_X 256
#define PLAYER_DEATH_FRAME_2_TEXTURE_REGION_X 280
#define PLAYER_DEATH_FRAME_3_TEXTURE_REGION_X 304
#define PLAYER_DEATH_FRAME_4_TEXTURE_REGION_X 328
#define PLAYER_DEATH_FRAME_5_TEXTURE_REGION_X 352
#define PLAYER_DEATH_FRAME_6_TEXTURE_REGION_X 376
#define PLAYER_DEATH_FRAME_7_TEXTURE_REGION_X 400

#define BOMB_FRAME_1_TEXTURE_REGION_X 432
#define BOMB_FRAME_1_TEXTURE_REGION_Y 40
#define BOMB_FRAME_2_TEXTURE_REGION_X 456
#define BOMB_FRAME_2_TEXTURE_REGION_Y 40
#define BOMB_FRAME_3_TEXTURE_REGION_X 480
#define BOMB_FRAME_3_TEXTURE_REGION_Y 40
#define BOMB_TEXTURE_REGION_WIDTH 20
#define BOMB_TEXTURE_REGION_HEIGHT 24

#define EXPLOSION_CORE_FRAME_1_TEXTURE_REGION_X 328
#define EXPLOSION_CORE_FRAME_1_TEXTURE_REGION_Y 96
#define EXPLOSION_CORE_FRAME_2_TEXTURE_REGION_X 328
#define EXPLOSION_CORE_FRAME_2_TEXTURE_REGION_Y 168
#define EXPLOSION_CORE_FRAME_3_TEXTURE_REGION_X 328
#define EXPLOSION_CORE_FRAME_3_TEXTURE_REGION_Y 240
#define EXPLOSION_CORE_FRAME_4_TEXTURE_REGION_X 328
#define EXPLOSION_CORE_FRAME_4_TEXTURE_REGION_Y 320

#define EXPLOSION_BODY_FRAME_1_TEXTURE_REGION_X 352
#define EXPLOSION_BODY_FRAME_1_TEXTURE_REGION_Y 96
#define EXPLOSION_BODY_FRAME_2_TEXTURE_REGION_X 352
#define EXPLOSION_BODY_FRAME_2_TEXTURE_REGION_Y 168
#define EXPLOSION_BODY_FRAME_3_TEXTURE_REGION_X 352
#define EXPLOSION_BODY_FRAME_3_TEXTURE_REGION_Y 240
#define EXPLOSION_BODY_FRAME_4_TEXTURE_REGION_X 352
#define EXPLOSION_BODY_FRAME_4_TEXTURE_REGION_Y 320

#define EXPLOSION_TAIL_FRAME_1_TEXTURE_REGION_X 376
#define EXPLOSION_TAIL_FRAME_1_TEXTURE_REGION_Y 96
#define EXPLOSION_TAIL_FRAME_2_TEXTURE_REGION_X 376
#define EXPLOSION_TAIL_FRAME_2_TEXTURE_REGION_Y 168
#define EXPLOSION_TAIL_FRAME_3_TEXTURE_REGION_X 376
#define EXPLOSION_TAIL_FRAME_3_TEXTURE_REGION_Y 240
#define EXPLOSION_TAIL_FRAME_4_TEXTURE_REGION_X 376
#define EXPLOSION_TAIL_FRAME_4_TEXTURE_REGION_Y 320

#define EXPLOSION_TEXTURE_REGION_WIDTH 16
#define EXPLOSION_TEXTURE_REGION_HEIGHT 16

#include <vector>

class TextureRegion;
class InsideBlock;
class BreakableBlock;
class PlayerDynamicGameObject;
class BombGameObject;
class Explosion;
class PowerUp;

class Assets
{
public:
	static Assets * getInstance();
    
    static TextureRegion getWorldBackgroundTextureRegion();
    
    static TextureRegion getInsideBlockTextureRegion();

	static TextureRegion getBreakableBlockTextureRegion();
    
    static TextureRegion getInterfaceOverlayTextureRegion();
    
    static TextureRegion getDPadControlTextureRegion();
	
	static TextureRegion getActiveButtonTextureRegion();

	static TextureRegion getPowerUpTextureRegion(PowerUp &powerUp);
    
    static TextureRegion getPlayerTextureRegion(PlayerDynamicGameObject &player);
    
    static TextureRegion getBombTextureRegion(BombGameObject &bomb);
    
    static TextureRegion getExplosionTextureRegion(Explosion &explosion);
    
    void setMusicId(short musicId);
    
    short getMusicId();
    
    short getFirstSoundId();
    
    void addSoundIdToPlayQueue(short soundId);
    
    void eraseFirstSoundId();

private:
    Assets();
    
    static int getKeyFrameNumber(float stateTime, float cycleTime, std::vector<float> &frameDurations);
    
    std::vector<short> m_sSoundIds;
    short m_sMusicId;
};

#endif /* defined(__bomber_party__Assets__) */