//
//  GameConstants.h
//  bomber-party
//
//  Created by Stephen Gowen on 5/13/14.
//  Copyright (c) 2014 Techne Games. All rights reserved.
//

#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define SCREEN_WIDTH 24.0f
#define SCREEN_HEIGHT 13.6119403f

#define GAME_X 1.43283582f
#define GAME_Y 2.86567164210521f
#define GAME_BORDER_RIGHT_WIDTH 1.07462686567176f
#define GAME_BORDER_TOP_HEIGHT 1.43283582105267f
#define GAME_WIDTH SCREEN_WIDTH - GAME_X - GAME_BORDER_RIGHT_WIDTH
#define GAME_HEIGHT SCREEN_HEIGHT * 2 - GAME_Y - GAME_BORDER_TOP_HEIGHT

#define GRID_CELL_WIDTH 1.43283582f
#define GRID_CELL_HEIGHT 1.43283582f

#define GRID_CELL_NUM_ROWS 16
#define NUM_GRID_CELLS_PER_ROW 15

#define PLAYER_WIDTH GRID_CELL_WIDTH * 2.0f / 3.0f
#define PLAYER_HEIGHT GRID_CELL_HEIGHT * 4.0f / 5.0f

#define PLAYER_FRAME_WIDTH PLAYER_WIDTH * 3
#define PLAYER_FRAME_HEIGHT PLAYER_HEIGHT * 2

#define PLAYER_STARTING_X_LEFT GAME_X + GRID_CELL_WIDTH / 2.0f
#define PLAYER_STARTING_X_RIGHT GAME_X + GAME_WIDTH - GRID_CELL_WIDTH / 2.0f
#define PLAYER_STARTING_Y_TOP GAME_Y + GAME_HEIGHT
#define PLAYER_STARTING_Y_BOTTOM GAME_Y + GRID_CELL_HEIGHT / 2.0f

#define PLAYER_STARTING_GRID_CELL_BOTTOM_HALF_TOP 6
#define PLAYER_STARTING_GRID_CELL_TOP_HALF_BOTTOM 9

#define PLAYER_STARTING_Y_BOTTOM_HALF_TOP GAME_Y + PLAYER_STARTING_GRID_CELL_BOTTOM_HALF_TOP * GRID_CELL_HEIGHT + GRID_CELL_HEIGHT / 2.0f
#define PLAYER_STARTING_Y_TOP_HALF_BOTTOM GAME_Y + PLAYER_STARTING_GRID_CELL_TOP_HALF_BOTTOM * GRID_CELL_HEIGHT + GRID_CELL_HEIGHT / 2.0f

#define DIRECTION_RIGHT 0
#define DIRECTION_UP 1
#define DIRECTION_LEFT 2
#define DIRECTION_DOWN 3

#define FRICTION_FACTOR 0.0015f

#endif /* GAME_CONSTANTS_H */
