//
//  GameConstants.h
//  bomber-party
//
//  Created by Stephen Gowen on 5/13/14.
//  Copyright (c) 2014 Techne Games. All rights reserved.
//

#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define SCREEN_WIDTH 24.0f
#define SCREEN_HEIGHT 13.5f

#define GAME_X 3.41422584f
#define GAME_Y 2.91891897f
#define GAME_WIDTH 19.0f
#define GAME_HEIGHT 21.25f

#define GRID_CELL_WIDTH 1.0f
#define GRID_CELL_HEIGHT 1.25f

#define GRID_CELL_NUM_ROWS GAME_HEIGHT / GRID_CELL_HEIGHT
#define NUM_GRID_CELLS_PER_ROW GAME_WIDTH / GRID_CELL_WIDTH

#define PLAYER_WIDTH GRID_CELL_WIDTH * 2.0f / 3.0f
#define PLAYER_HEIGHT GRID_CELL_HEIGHT * 4.0f / 5.0f

#define PLAYER_FRAME_WIDTH PLAYER_WIDTH * 3
#define PLAYER_FRAME_HEIGHT PLAYER_HEIGHT * 2

#define PLAYER_STARTING_X_LEFT GAME_X + PLAYER_WIDTH / 2.0f
#define PLAYER_STARTING_X_RIGHT GAME_X + GAME_WIDTH - PLAYER_WIDTH / 2.0f
#define PLAYER_STARTING_Y_TOP GAME_Y + GAME_HEIGHT
#define PLAYER_STARTING_Y_BOTTOM GAME_Y + PLAYER_HEIGHT / 2.0f

#define PLAYER_STARTING_GRID_CELL_BOTTOM_HALF_TOP 8
#define PLAYER_STARTING_GRID_CELL_TOP_HALF_BOTTOM 10

#define PLAYER_STARTING_Y_BOTTOM_HALF_TOP GAME_Y + PLAYER_STARTING_GRID_CELL_BOTTOM_HALF_TOP * GRID_CELL_HEIGHT + PLAYER_HEIGHT / 2.0f
#define PLAYER_STARTING_Y_TOP_HALF_BOTTOM GAME_Y + PLAYER_STARTING_GRID_CELL_TOP_HALF_BOTTOM * GRID_CELL_HEIGHT + PLAYER_HEIGHT / 2.0f

#define DIRECTION_RIGHT 0
#define DIRECTION_UP 1
#define DIRECTION_LEFT 2
#define DIRECTION_DOWN 3

#define FRICTION_FACTOR 0.0015f

#endif /* GAME_CONSTANTS_H */
