//
//  GameEvent.h
//  battlebombs
//
//  Created by Stephen Gowen on 3/15/14.
//  Copyright (c) 2014 Gowen Game Dev. All rights reserved.
//

#ifndef GAME_EVENT_H
#define GAME_EVENT_H

// Event Type
#define PRE_GAME 1334
#define PRE_GAME_SERVER_UPDATE 1335
#define BEGIN_SPECTATE 1336
#define BEGIN_GAME 1337
#define CLIENT_UPDATE 1338
#define SUDDEN_DEATH 1339
#define GAME_OVER 1340
#define HARD_UPDATE 1341

// Map Type
#define MAP_SPACE 0
#define MAP_GRASSLANDS 1
#define MAP_MOUNTAINS 2
#define MAP_BASE 3
#define NUM_MAPS 4

// Pre Game Phases
#define DEFAULT 0
#define CONNECTING 1
#define FINDING_ROOM_TO_JOIN 2
#define ROOM_JOINED_WAITING_FOR_SERVER 3
#define CONNECTION_ERROR 4

// Platform
#define PLATFORM_UNKNOWN 0
#define PLATFORM_ANDROID 1
#define PLATFORM_IOS 2
#define PLATFORM_WINDOWS_PHONE 3

// Event Player Data
#define PLAYER_EVENT_BASE 100000000
#define PLAYER_EVENT_DIRECTION_BASE 10000000
#define PLAYER_EVENT_GRID_X_BASE 100000
#define PLAYER_EVENT_GRID_Y_BASE 1000
#define PLAYER_EVENT_MOD_BASE 100

// Events
#define PLAYER_MOVE_RIGHT 1
#define PLAYER_MOVE_UP 2
#define PLAYER_MOVE_LEFT 3
#define PLAYER_MOVE_DOWN 4
#define PLAYER_MOVE_STOP 5
#define PLAYER_PLANT_BOMB 6
#define PLAYER_PLANT_REMOTE_BOMB 7
#define PLAYER_PUSH_BOMB 8
#define PLAYER_RAISE_SHIELD 9
#define PLAYER_LOWER_SHIELD 10
#define PLAYER_FORCE_FIELD_HIT 11
#define PLAYER_DEATH 12
#define PLAYER_HIT_BY_FIRE_BALL 13
#define PLAYER_ABOUT_TO_FALL 14
#define PLAYER_FALL 15
#define PLAYER_FREEZE 16
#define PLAYER_DETONATE_BOMB 17
#define PLAYER_TRIGGER_LANDMINE 18
#define PLAYER_PLACE_LANDMINE 19
#define PLAYER_PU_BOMB 30
#define PLAYER_PU_FIRE 31
#define PLAYER_PU_SPEED 32
#define PLAYER_PU_FORCE_FIELD 33
#define PLAYER_PU_PUSH 34
#define PLAYER_PU_SHIELD 35
#define PLAYER_PU_MEGA_FIRE 36
#define PLAYER_PU_REMOTE_BOMB 37
#define PLAYER_PU_LAND_MINE 38
#define PLAYER_PU_CURSE 39

#endif /* GAME_EVENT_H */
